/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BaptismRouteImport } from './routes/baptism'
import { Route as BelieveRouteImport } from './routes/believe'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EventsRouteImport } from './routes/events'
import { Route as GiveRouteImport } from './routes/give'
import { Route as MinistriesRouteImport } from './routes/ministries'
import { Route as NewsRouteImport } from './routes/news'
import { Route as PrayerRouteImport } from './routes/prayer'
import { Route as VisitRouteImport } from './routes/visit'
import { Route as WorshipRouteImport } from './routes/worship'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BaptismRoute = BaptismRouteImport.update({
  id: '/baptism',
  path: '/baptism',
  getParentRoute: () => rootRouteImport,
} as any)
const BelieveRoute = BelieveRouteImport.update({
  id: '/believe',
  path: '/believe',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const GiveRoute = GiveRouteImport.update({
  id: '/give',
  path: '/give',
  getParentRoute: () => rootRouteImport,
} as any)
const MinistriesRoute = MinistriesRouteImport.update({
  id: '/ministries',
  path: '/ministries',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayerRoute = PrayerRouteImport.update({
  id: '/prayer',
  path: '/prayer',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitRoute = VisitRouteImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => rootRouteImport,
} as any)
const WorshipRoute = WorshipRouteImport.update({
  id: '/worship',
  path: '/worship',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/baptism': typeof BaptismRoute
  '/believe': typeof BelieveRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/give': typeof GiveRoute
  '/ministries': typeof MinistriesRoute
  '/news': typeof NewsRoute
  '/prayer': typeof PrayerRoute
  '/visit': typeof VisitRoute
  '/worship': typeof WorshipRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/baptism': typeof BaptismRoute
  '/believe': typeof BelieveRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/give': typeof GiveRoute
  '/ministries': typeof MinistriesRoute
  '/news': typeof NewsRoute
  '/prayer': typeof PrayerRoute
  '/visit': typeof VisitRoute
  '/worship': typeof WorshipRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/baptism': typeof BaptismRoute
  '/believe': typeof BelieveRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/give': typeof GiveRoute
  '/ministries': typeof MinistriesRoute
  '/news': typeof NewsRoute
  '/prayer': typeof PrayerRoute
  '/visit': typeof VisitRoute
  '/worship': typeof WorshipRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/baptism'
    | '/believe'
    | '/contact'
    | '/events'
    | '/give'
    | '/ministries'
    | '/news'
    | '/prayer'
    | '/visit'
    | '/worship'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/baptism'
    | '/believe'
    | '/contact'
    | '/events'
    | '/give'
    | '/ministries'
    | '/news'
    | '/prayer'
    | '/visit'
    | '/worship'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/baptism'
    | '/believe'
    | '/contact'
    | '/events'
    | '/give'
    | '/ministries'
    | '/news'
    | '/prayer'
    | '/visit'
    | '/worship'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BaptismRoute: typeof BaptismRoute
  BelieveRoute: typeof BelieveRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  GiveRoute: typeof GiveRoute
  MinistriesRoute: typeof MinistriesRoute
  NewsRoute: typeof NewsRoute
  PrayerRoute: typeof PrayerRoute
  VisitRoute: typeof VisitRoute
  WorshipRoute: typeof WorshipRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baptism': {
      id: '/baptism'
      path: '/baptism'
      fullPath: '/baptism'
      preLoaderRoute: typeof BaptismRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/believe': {
      id: '/believe'
      path: '/believe'
      fullPath: '/believe'
      preLoaderRoute: typeof BelieveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/give': {
      id: '/give'
      path: '/give'
      fullPath: '/give'
      preLoaderRoute: typeof GiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ministries': {
      id: '/ministries'
      path: '/ministries'
      fullPath: '/ministries'
      preLoaderRoute: typeof MinistriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayer': {
      id: '/prayer'
      path: '/prayer'
      fullPath: '/prayer'
      preLoaderRoute: typeof PrayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visit': {
      id: '/visit'
      path: '/visit'
      fullPath: '/visit'
      preLoaderRoute: typeof VisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worship': {
      id: '/worship'
      path: '/worship'
      fullPath: '/worship'
      preLoaderRoute: typeof WorshipRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BaptismRoute: BaptismRoute,
  BelieveRoute: BelieveRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  GiveRoute: GiveRoute,
  MinistriesRoute: MinistriesRoute,
  NewsRoute: NewsRoute,
  PrayerRoute: PrayerRoute,
  VisitRoute: VisitRoute,
  WorshipRoute: WorshipRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
